include ../sdk.mk

CATEGORIES=\
org.argeo.tp.sdk \
osgi/api/org.argeo.tp.osgi \
osgi/equinox/org.argeo.tp.osgi \
osgi/equinox/org.argeo.tp.eclipse \
swt/rap/org.argeo.tp.swt \
swt/rap/org.argeo.tp.swt.workbench \
swt/rcp/org.argeo.tp.swt \
lib/linux/x86_64/swt/rcp/org.argeo.tp.swt \
lib/linux/aarch64/swt/rcp/org.argeo.tp.swt \
lib/win32/x86_64/swt/rcp/org.argeo.tp.swt \
lib/macosx/x86_64/swt/rcp/org.argeo.tp.swt \
lib/macosx/x86_64/swt/rcp/org.argeo.tp.swt.workbench \
swt/rcp/org.argeo.tp.swt \
swt/rcp/org.argeo.tp.swt.workbench \
org.argeo.tp \
org.argeo.tp.httpd \
org.argeo.tp.utils \
org.argeo.tp.publish \
org.argeo.tp.math \
org.argeo.tp.jcr \
org.argeo.tp.office \
org.argeo.tp.earth \
crypto/full/org.argeo.tp.crypto \
crypto/fips/org.argeo.tp.crypto \

# NOTE: FIPS support is experimental, in order to preapre for the 2.0.0 stream
# see https://www.bouncycastle.org/fips_java_roadmap.html

include  $(SDK_SRC_BASE)/sdk/argeo-build/repackage.mk