eclipse-equinox=http://www.eclipse.org/downloads/equinox/drops/R-4.37-202509050730/equinox-SDK-4.37.zip
eclipse-rcp=http://www.eclipse.org/downloads/eclipse/downloads/drops4/R-4.37-202509050730/eclipse-SDK-4.37-win32-x86_64.zip
eclipse-rcp-multiarch=http://www.eclipse.org/downloads/eclipse/downloads/drops4/R-4.37-202509050730/org.eclipse.platform-4.37.zip
eclipse-rap=http://www.eclipse.org/downloads/rt/rap/4.4/e4/rap-e4-4.4.0-R-20250829-0703.zip
# Nebula does not seem to provide archives anymore, 3.1.0 is available only as an update site
#eclipse-nebula=http://www.eclipse.org/downloads/nebula/releases/3.0.0/repository-nebula-3.0.0.zip
