/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_mail_mbox_UNIXFile */

#ifndef _Included_com_sun_mail_mbox_UNIXFile
#define _Included_com_sun_mail_mbox_UNIXFile
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_mail_mbox_UNIXFile_serialVersionUID
#define com_sun_mail_mbox_UNIXFile_serialVersionUID 301077366599181567LL
#undef com_sun_mail_mbox_UNIXFile_serialVersionUID
#define com_sun_mail_mbox_UNIXFile_serialVersionUID -7972156315284146651LL
#undef com_sun_mail_mbox_UNIXFile_NONE
#define com_sun_mail_mbox_UNIXFile_NONE 0L
#undef com_sun_mail_mbox_UNIXFile_NATIVE
#define com_sun_mail_mbox_UNIXFile_NATIVE 1L
#undef com_sun_mail_mbox_UNIXFile_JAVA
#define com_sun_mail_mbox_UNIXFile_JAVA 2L
/*
 * Class:     com_sun_mail_mbox_UNIXFile
 * Method:    initIDs
 * Signature: (Ljava/lang/Class;Ljava/io/FileDescriptor;)V
 */
JNIEXPORT void JNICALL Java_com_sun_mail_mbox_UNIXFile_initIDs
  (JNIEnv *, jclass, jclass, jobject);

/*
 * Class:     com_sun_mail_mbox_UNIXFile
 * Method:    lock0
 * Signature: (Ljava/io/FileDescriptor;Ljava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_mail_mbox_UNIXFile_lock0
  (JNIEnv *, jclass, jobject, jstring, jboolean);

/*
 * Class:     com_sun_mail_mbox_UNIXFile
 * Method:    lastAccessed0
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_sun_mail_mbox_UNIXFile_lastAccessed0
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
