/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_mail_mbox_UNIXInbox */

#ifndef _Included_com_sun_mail_mbox_UNIXInbox
#define _Included_com_sun_mail_mbox_UNIXInbox
#ifdef __cplusplus
extern "C" {
#endif
#undef com_sun_mail_mbox_UNIXInbox_serialVersionUID
#define com_sun_mail_mbox_UNIXInbox_serialVersionUID 301077366599181567LL
#undef com_sun_mail_mbox_UNIXInbox_serialVersionUID
#define com_sun_mail_mbox_UNIXInbox_serialVersionUID -7972156315284146651LL
#undef com_sun_mail_mbox_UNIXInbox_NONE
#define com_sun_mail_mbox_UNIXInbox_NONE 0L
#undef com_sun_mail_mbox_UNIXInbox_NATIVE
#define com_sun_mail_mbox_UNIXInbox_NATIVE 1L
#undef com_sun_mail_mbox_UNIXInbox_JAVA
#define com_sun_mail_mbox_UNIXInbox_JAVA 2L
#undef com_sun_mail_mbox_UNIXInbox_serialVersionUID
#define com_sun_mail_mbox_UNIXInbox_serialVersionUID -254578891263785591LL
#undef com_sun_mail_mbox_UNIXInbox_serialVersionUID
#define com_sun_mail_mbox_UNIXInbox_serialVersionUID 651261842162777620LL
/*
 * Class:     com_sun_mail_mbox_UNIXInbox
 * Method:    maillock
 * Signature: (Ljava/lang/String;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_sun_mail_mbox_UNIXInbox_maillock
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_sun_mail_mbox_UNIXInbox
 * Method:    mailunlock
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_mail_mbox_UNIXInbox_mailunlock
  (JNIEnv *, jobject);

/*
 * Class:     com_sun_mail_mbox_UNIXInbox
 * Method:    touchlock0
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sun_mail_mbox_UNIXInbox_touchlock0
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
