.PHONY: clean all

all:
	make -C org.argeo.tp.sys
	make -C org.argeo.tp.ml

install:
	make -C org.argeo.tp.sys install
	make -C org.argeo.tp.ml install
	
uninstall:
	make -C org.argeo.tp.sys uninstall
	make -C org.argeo.tp.ml uninstall
	
clean:
	make -C org.argeo.tp.sys clean
	make -C org.argeo.tp.ml clean
	